# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.__config__)

1.13.3
<module 'numpy.__config__' from 'C:\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
arr1 = np.empty(10)
arr1

array([  2.41907520e-312,   1.03977794e-312,   1.29441743e-312,
         2.33419537e-312,   9.76118064e-313,   2.31297541e-312,
         2.46151512e-312,   8.48798317e-313,   1.01855798e-312,
         2.02566915e-322])

#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
print(arr1.nbytes / 1024.0) 

0.078125


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.  If ``x1.shape != x2.shape``, they must be\n    broadcastable to a common shape (which may be the shape of one or\n    the other).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or `None`,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    Values of True indicate to calculate the ufunc at that position, values\n    of False indicate to leave the value in the output alone.\n**kwargs\n    For other keyword-only arguments, see the\n    :ref:`ufunc docs <ufuncs.kwargs>`.\n\nReturns\n-------\nadd : 

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
arr2 = np.empty(10)
arr2[4] = 1
arr2

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
arr3 = np.arange(10,50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [12]:
arr3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
arr4 = np.arange(9).reshape(3,-1)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [15]:
arr5 = np.array([1,2,0,0,4,0])
np.nonzero(arr5)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
arr5 = np.random.randn(27).reshape((3,3,3))
arr5

array([[[ 0.27409555,  0.07505727, -0.19119591],
        [ 0.55670855,  0.24593455,  0.46460348],
        [-0.59061547,  2.20765956,  0.61068417]],

       [[-0.37831367,  0.28993999, -1.78864956],
        [ 0.69267153,  0.52134723,  0.66623921],
        [-2.10460379, -1.05947416, -0.73649033]],

       [[-0.04458397,  0.14678736,  0.2154269 ],
        [ 0.71843853, -1.13418078,  0.36967869],
        [ 1.35358944,  0.96639876, -0.12861869]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
arr5 = np.random.randn(100)
np.min(arr5), np.max(arr5)

(-2.7500864286075859, 2.1204865121255523)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
arr5 = np.random.randn(100)
np.mean(arr5)

0.036810605285859249

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
arr5 = np.zeros((2,3))
np.pad(arr5, ((1,1),(1,1)),'constant', constant_values=1)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [27]:
arr5 = np.random.randn(6).reshape((2,3))
np.pad(arr5, ((1,1),(1,1)),'constant', constant_values=0)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.59308894,  0.38331618,  0.10596601,  0.        ],
       [ 0.        ,  0.74059362,  1.65912036,  0.30817251,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [29]:
# 0
# np.nan
# np.nan
# np.nan
# False


print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
False
False
nan
False


Python 3.5 adds the math.isclose and cmath.isclose functions as described in PEP 485.

If you're using an earlier version of Python, the equivalent function is given in the documentation.

```Python
def isclose(a, b, rel_tol=1e-09, abs_tol=0.0):
    return abs(a-b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)
```   

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
np.diag(np.arange(4)+1, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [40]:
arr5 = np.zeros((8,8))
print(arr5)
arr5[1::2,::2] = 1
print(arr5)
arr5[::2,1::2] = 1
print(arr5)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]
[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [41]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [49]:
m = np.diag((1,),k=(-1)) + np.diag((1,),k=(1))
n = np.tile(m,reps=(4,4))
n

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [50]:
m = np.random.random((5,5))
m_min, m_max = np.min(m), np.max(m)
m = (m - m_min) / (m_max - m_min)
m

array([[ 0.63796844,  0.24936357,  0.14710172,  1.        ,  0.29786824],
       [ 0.2257852 ,  0.35994772,  0.7377235 ,  0.        ,  0.1786023 ],
       [ 0.47935763,  0.8231628 ,  0.39315412,  0.95626703,  0.25089195],
       [ 0.86555171,  0.45435492,  0.50565363,  0.48676936,  0.97203373],
       [ 0.85136309,  0.77667325,  0.22359449,  0.94542704,  0.79469511]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [54]:
m1 = np.arange(15).reshape((5,3))
m2 = np.arange(6).reshape((3,2))
print(np.matmul(m1,m2))
print(np.dot(m1, m2))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [56]:
arr1 = np.arange(10)
arr1[(arr1 > 3) & (arr1 < 8)] *= -1
arr1

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [60]:
# 5
# 15
print(range(5)[0:-1])
print(sum(range(5),-1))
print(np.sum(range(5),-1))

range(0, 4)
9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [62]:
# np.nan
# np.nan
# np.nan

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -2.14748365e+09]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [70]:
arr1 = np.random.randn(10)
print(arr1)
arr1[arr1 < 0] = -np.ceil(-arr1[arr1 < 0]) 
arr1[arr1 > 0] = np.ceil(arr1[arr1 > 0])
arr1

# better solution
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 0.8161173   0.22081875 -0.69612615  0.03679116 -0.29916065 -0.73213525
  1.17359103  0.79975687 -1.17392157  0.36935395]
[  1.  -4.   4.  -5.  -1. -10.   8. -10.   5.   8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [72]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(arr1)
print(arr2)
print(np.intersect1d(arr1, arr2))

[1 1 3 5 8 3 2 8 0 6]
[5 1 6 8 3 8 3 0 0 0]
[0 1 3 5 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [73]:
np.datetime64('today') - np.timedelta64(1, 'D')

numpy.datetime64('2018-02-07')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [75]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)